### ISSUE TITLE
Laser beams hit robot chassis

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_common#205]
![issue](https://user-images.githubusercontent.com/2829645/28070162-4463b5ac-664c-11e7-9234-e53ecdce70c8.png)
Hi,
I noticed that the laser scan hits the robot chassis.

**Comment by ipa-nhg** [comment]
https://github.com/squirrel-project/squirrel_common/pull/206 should solve the issue, please test

**Comment by ghost** [comment]
Not really, with robot:=alufr-robotino I can see the profile (another profile, maybe the arm)

**Comment by ipa-nhg** [comment]
please send a screenshot also activating the RobotModel collision!

 I guess you are using the simulation and the current upstream version.

**Comment by ipa-nhg** [comment]
solved
