### ISSUE TITLE
[rospack] Error: package 'soft_hand_description' not found

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_common#216]
Since yesterday I have issues displaying the robot model in Rviz. It worked until around 4 pm, since then - even after a fresh build of the workspace - the error persists.

**Comment by ipa-nhg** [comment]
which version do you have? soft_hand_description was the old version

**Comment by ghost** [comment]
As said, I fetched the upstream yesterday at around 19:00 and compiled after that (which was an adventure). The fun thing - it worked until yesterday afternoon and suddenly stopped. Figuring out right now what goes wrong. Working on indigo_dev.

**Comment by ipa-nhg** [comment]
```
roscd squirrel_common
git log
```

which one is the last commit?

```
roscd squirrel_common
grep -R soft_hand_description 
```
which URDF file depend on soft_hand_description ?? For the upstream repository I can only find it on the history files https://github.com/squirrel-project/squirrel_common/search?utf8=%E2%9C%93&q=soft_hand_description&type=

**Comment by ghost** [comment]
The latest commit is

`3fe3f8333dcd88090381f2862c87c92d8df4f793`

and the grep command just yields the changelog files (which is fine). It's just that Rviz is complaining when adding the robot model. I'll send you the error via mail.

**Comment by ipa-nhg** [comment]
could you try the same for squirrel_robotino?

believe that you are starting the bringup on the robot and rviz locally? is this the case? are you sure that the robot and the local pc have the same version?

**Comment by ghost** [comment]
last commit: `7a05bd558296fba6ec76651178a7bca6fae0b655`

Grep finds nothing. 

Just updating the robot and compiling again. If this is the issue, my bad! Keeping you updated.

**Comment by ghost** [comment]
Same version now on the robot and locally but error persists. But anyways, our arm just stopped working again - can't connect (@mzillich - this is really horrible...)

**Comment by ipa-nhg** [comment]
`rosparam get /robot_description | grep soft_hand_description`

**Comment by ghost** [comment]
This yields quite some output:

`\ simulation fails -->\n  \n  \n  \n  \n  <!-- MESHLAB RESULT \nOpened mesh /home/crosales/Code/catkin_ws/src/pisa-iit-soft-hand/soft_hand/soft_hand_description/meshes/palm_right.stl\
  \ xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/wrist.stl\"\
  \ filename=\"package://soft_hand_description/meshes/wrist.stl\"/>\n      </geometry>\n\
  \ xyz=\"-0.02 -0.145 0.07\"/>\n      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/robotino_softhand_adapter_scaled.stl\"\
  \        <mesh filename=\"package://soft_hand_description/meshes/robotino_softhand_adapter_scaled.stl\"\
  package://soft_hand_description/meshes/accesories/clamp.stl\"/>\n      </geometry>\n\
  \        <mesh filename=\"package://soft_hand_description/meshes/accesories/softhand_base_right.stl\"\
  \      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/palm_right.stl\"\
  package://soft_hand_description/meshes/palm_right_collision.stl\" scale=\" .001\
  \      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/thumb_knuckle_right.stl\"\
  package://soft_hand_description/meshes/thumb_knuckle_right_collision.stl\" scale=\"\
  \        <mesh filename=\"package://soft_hand_description/meshes/phalanx.stl\" scale=\"\
  package://soft_hand_description/meshes/phalanx_collision.stl\" scale=\" .001 .001\
  />\n    </inertial>\n    <visual>\n      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/fingertip.stl\"\
  package://soft_hand_description/meshes/fingertip_collision.stl\" scale=\" .001 .001\
  \        <mesh filename=\"package://soft_hand_description/meshes/knuckle.stl\" scale=\"\
  package://soft_hand_description/meshes/knuckle_collision.stl\" scale=\" .001 .001\
  \        <mesh filename=\"package://soft_hand_description/meshes/phalanx.stl\" scale=\"\
  package://soft_hand_description/meshes/phalanx_collision.stl\" scale=\" .001 .001\
  package://soft_hand_description/meshes/phalanx.stl\" scale=\" .001 .001 .001\"/>\n\
  \    <collision>\n      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/phalanx_collision.stl\"\
  />\n    </inertial>\n    <visual>\n      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/fingertip.stl\"\
  package://soft_hand_description/meshes/fingertip_collision.stl\" scale=\" .001 .001\
  \  <mesh filename=\"package://soft_hand_description/meshes/knuckle.stl\" scale=\"\
  package://soft_hand_description/meshes/knuckle_collision.stl\" scale=\" .001 .001\
  \      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/phalanx.stl\"\
  package://soft_hand_description/meshes/phalanx_collision.stl\" scale=\" .001 .001\
  \      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/phalanx.stl\"\
  package://soft_hand_description/meshes/phalanx_collision.stl\" scale=\" .001 .001\
  \    <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/fingertip.stl\"\
  package://soft_hand_description/meshes/fingertip_collision.stl\" scale=\" .001 .001\
  \        <mesh filename=\"package://soft_hand_description/meshes/knuckle.stl\" scale=\"\
  package://soft_hand_description/meshes/knuckle_collision.stl\" scale=\" .001 .001\
  package://soft_hand_description/meshes/phalanx.stl\" scale=\" .001 .001 .001\"/>\n\
  \    <collision>\n      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/phalanx_collision.stl\"\
  />\n    </inertial>\n    <visual>\n      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/phalanx.stl\"\
  package://soft_hand_description/meshes/phalanx_collision.stl\" scale=\" .001 .001\
  \    <visual>\n      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/fingertip.stl\"\
  package://soft_hand_description/meshes/fingertip_collision.stl\" scale=\" .001 .001\
  \        <mesh filename=\"package://soft_hand_description/meshes/knuckle.stl\" scale=\"\
  package://soft_hand_description/meshes/knuckle_collision.stl\" scale=\" .001 .001\
  \      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/phalanx.stl\"\
  package://soft_hand_description/meshes/phalanx_collision.stl\" scale=\" .001 .001\
  \      <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/phalanx.stl\"\
  package://soft_hand_description/meshes/phalanx_collision.stl\" scale=\" .001 .001\
  \    <geometry>\n        <mesh filename=\"package://soft_hand_description/meshes/fingertip.stl\"\
  package://soft_hand_description/meshes/fingertip_collision.stl\" scale=\" .001 .001\
`

But what did change when it worked previously and suddenly stops?

**Comment by ghost** [comment]
Did this on the robot with the reported commits

**Comment by ipa-nhg** [comment]
you are including the old model of the hand or the it_robotics version (?) , probably the urdf of the robot is old or modified.

on the robot check the file:

`robotino_bringup/robots/uibk-robotino2-sh/urdf/robotino.urdf.xacro `

Are you including `$(find softhand_description)/model/softhand_withCableCanal.urdf.xacro` ? if yes check the mesh import of the file:

` squirrel_common/softhand_description/model/soft_hand_fixed.urdf.xacro`

**Comment by ghost** [comment]
Oh snap, I think I found the problem: the overlay. The squirrel user's WS was never updated and still contained that package. Trying to fix it now by updating and rebuilding. That most likely fixed it but as our arm is broken again (@mzillich) I'll let you know asap whether it really was the issue. In this case, sorry, my bad - totally forgot about the overlay.

**Comment by ghost** [comment]
Seems to be gone.
